<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Po box_test</name>
   <tag></tag>
   <elementGuidId>735ec16b-05f0-43ee-ba84-09ef51c1888b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='test']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;test&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27ce2638-c7b5-42df-9e12-f802d8725dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss14</value>
      <webElementGuid>2035ea21-c6c7-4c21-9dbf-c351d01f9594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>d1ff2bd6-ba72-40e9-883e-8821b3ccabbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f469a903-d9eb-4f89-8ec3-607cc0bacfd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>162</value>
      <webElementGuid>b0ce4a57-2188-475b-bf4a-8231ba7db66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/section[@class=&quot;registrationCnt&quot;]/div[@class=&quot;registration&quot;]/div[@class=&quot;plBox&quot;]/div[@class=&quot;regContainer container&quot;]/form[1]/div[@class=&quot;row mt-4&quot;]/div[@class=&quot;col-sm-6 col-12&quot;]/div[@class=&quot;RadioBox&quot;]/div[@class=&quot;MuiFormGroup-root&quot;]/label[@class=&quot;MuiFormControlLabel-root checked&quot;]/span[@class=&quot;MuiButtonBase-root MuiIconButton-root jss11 MuiRadio-root jss9 jss12 Mui-checked jss10&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/input[@class=&quot;jss14&quot;]</value>
      <webElementGuid>d5b6c11a-5e3d-4187-b20b-aa5244404fd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='test']</value>
      <webElementGuid>ab6ddd3e-066a-45db-969d-05ce0814e3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/div/div/div[2]/form/div/div[14]/div/div/label/span/span/input</value>
      <webElementGuid>097eec64-b214-4049-b9d1-3edfa0774217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>e400b831-31be-4849-ace9-e29dee35d3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'test' and @type = 'radio']</value>
      <webElementGuid>bbfef179-be2e-4d45-8b29-07ef7302862c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
