<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Male_test</name>
   <tag></tag>
   <elementGuidId>84c560b2-034d-42f2-9e60-4358a1ea9149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='test'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.MuiFormControlLabel-root.unChecked > span.MuiButtonBase-root.MuiIconButton-root.jss11.MuiRadio-root.jss9 > span.MuiIconButton-label > input[name=&quot;test&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a29d3db6-7bbe-4d22-a700-c61990c15d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss14</value>
      <webElementGuid>e95070a2-8dec-4791-9d8c-8b6de556cd13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>54ae392c-4653-46e7-bdb2-b188fd29a857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0a1c425e-ee4e-4bb9-a989-b854d6f8b83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>163</value>
      <webElementGuid>b4371010-8fc1-4693-b619-cbde279fd5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/section[@class=&quot;registrationCnt&quot;]/div[@class=&quot;registration&quot;]/div[@class=&quot;plBox&quot;]/div[@class=&quot;regContainer container&quot;]/form[1]/div[@class=&quot;row mt-4&quot;]/div[@class=&quot;col-sm-6 col-12&quot;]/div[@class=&quot;RadioBox&quot;]/div[@class=&quot;MuiFormGroup-root&quot;]/label[@class=&quot;MuiFormControlLabel-root unChecked&quot;]/span[@class=&quot;MuiButtonBase-root MuiIconButton-root jss11 MuiRadio-root jss9&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/input[@class=&quot;jss14&quot;]</value>
      <webElementGuid>51718a22-6ee5-4956-b8b3-205a452ab824</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='test'])[2]</value>
      <webElementGuid>b1af15b1-46e6-4752-8ef5-b10af694717a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/div/div/div[2]/form/div/div[14]/div/div/label[2]/span/span/input</value>
      <webElementGuid>5a092e2c-bbe7-4437-a361-ad8b5ace4701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span/span/input</value>
      <webElementGuid>f3df6dca-7e61-4077-b91e-4e8fdeb20a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'test' and @type = 'radio']</value>
      <webElementGuid>7fd0c1af-8676-4163-bec0-ff2416584688</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
